from typing import Protocol

from .models import ActivityRecord, MMPRule, Molecule, OffTargetCandidate, StructureReference, Target


class ActivityProvider(Protocol):
    def get_target_activities(self, target: Target) -> list[ActivityRecord]: ...
    def get_compound_target_profile(self, molecule: Molecule) -> list[ActivityRecord]: ...


class CompoundSearchProvider(Protocol):
    def resolve_exact_molecule(self, canonical_smiles: str) -> str | None: ...
    def search_similar_molecules(
        self,
        canonical_smiles: str,
        similarity_threshold: float,
        limit: int,
    ) -> list[dict]: ...
    def get_profiles_for_compounds(self, molecule_ids: list[str]) -> list[ActivityRecord]: ...


class TargetProvider(Protocol):
    def resolve_target(self, value: str, role: str) -> Target: ...
    def get_family_candidates(self, on_target: Target) -> list[Target]: ...
    def get_target_by_id(self, chembl_id: str, role: str) -> Target: ...
    def same_family(self, on_target: Target, candidate: Target) -> bool: ...
    def family_similarity(self, on_target: Target, candidate: Target) -> float: ...
    def is_supported_off_target(self, target: Target) -> bool: ...


class StructureProvider(Protocol):
    def get_representative_structure(self, target: Target) -> StructureReference | None: ...


class MMPExtractor(Protocol):
    def extract(self, paired_rows: list[dict]) -> list[MMPRule]: ...


class OffTargetSignalProvider(Protocol):
    def discover(self, molecule: Molecule, on_target: Target) -> list[OffTargetCandidate]: ...
